version: "3.9"

services:
  sewerage_rainfall:
    build:
      context: .

    ports:
      - "8000:8000"

    volumes:
      - ./app:/app

    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=sewerage_rainfall_db
      - DB_NAME=sewerage_rainfall
      - DB_USER=sewerage_rainfall_user
      - DB_PASS=testpass
      - OPENAPI_KEY=${OPENAPI_KEY}
      - OPENAPI_URL=${OPENAPI_URL}

    depends_on:
      - sewerage_rainfall_db

  sewerage_rainfall_db:
    image: postgres:13-alpine
    volumes:
      - sewerage-rainfall-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sewerage_rainfall
      - POSTGRES_USER=sewerage_rainfall_user
      - POSTGRES_PASSWORD=testpass

volumes:
  sewerage-rainfall-data:
